export type CreatureStatusCategory =
  | 'flocking'
  | 'fleeing'
  | 'searching'
  | 'hunting'
  | 'digesting';

export const CYCLE_MS = 2500;

export const CREATURE_STATUS_PHRASES: Record<CreatureStatusCategory, readonly string[]> = {
  flocking: [
    'Flocking',
    'Schooling',
    'Cruising',
    'Drifting',
    'Mingling',
    'Holding formation',
    'Synchronizing',
    'Going with the flow',
    'Vibing',
    'Coasting',
    'Socializing',
    'Keeping pace',
    'Meandering',
    'Grouping up',
    'Aligning',
    'Neighbor-watching',
    'Gliding',
    'Chilling',
    'Sticking together',
    'Swirling',
    'Milling about',
    'Wing-tipping',
    'Loitering',
    'Swaying',
    'Falling in line',
  ],
  fleeing: [
    'Fleeing',
    'Panicking',
    'Scattering',
    'Bolting',
    'Dodging',
    'Evading',
    'Zigzagging',
    'Escaping',
    'Nope-ing out',
    'Juking',
    'Veering off',
    'Freaking out',
    'Bailing',
    'Diving away',
    'Breaking formation',
    'Running scared',
    'Peeling away',
    'Swerving',
    'Ducking',
    'Hightailing it',
    'Losing the tail',
    'Adrenaline spiking',
    'Getting out of Dodge',
    'Scrambling',
    'Fleeing for dear life',
  ],
  searching: [
    'Searching',
    'Patrolling',
    'Prowling',
    'Scanning',
    'Stalking the shallows',
    'Sniffing around',
    'Cruising for prey',
    'On the prowl',
    'Casing the area',
    'Lurking',
    'Surveying',
    'Sweeping',
    'Circling',
    'Watching',
    'Biding time',
    'Trawling',
    'Combing the depths',
    'Sizing up options',
    'Waiting for an opening',
    'Drifting hungrily',
    'Keeping an eye out',
    'Plotting',
    'Scoping targets',
    'Reconnoitering',
    'Hungry',
  ],
  hunting: [
    'Hunting',
    'Pursuing',
    'Chasing',
    'Closing in',
    'Locking on',
    'Zeroing in',
    'Bearing down',
    'Going for the kill',
    'Striking',
    'Ambushing',
    'Running it down',
    'In hot pursuit',
    'Target acquired',
    'Committing',
    'Accelerating',
    'Homing in',
    'Cutting it off',
    'On the attack',
    'Charging',
    'Tightening the gap',
    'Diving in',
    'No escape',
    'Full send',
    'Snapping at heels',
    'Making a move',
  ],
  digesting: [
    'Digesting',
    'Resting',
    'Satiated',
    'Food coma',
    'Recharging',
    'Napping',
    'Sleeping it off',
    'Basking',
    'Content',
    'Loafing',
    'Chilling out',
    'Post-meal bliss',
    'Winding down',
    'Catching a breath',
    'Idling',
    'Marinating',
    'Ruminating',
    'Stewing',
    'Zoning out',
    'Nothing to see here',
    'Belly full',
    'Cooling off',
    'Taking five',
    'Slow-blinking',
    'Full',
  ],
};

function modulo(value: number, length: number): number {
  return ((value % length) + length) % length;
}

export function pickStatusPhrase(
  category: CreatureStatusCategory,
  entityId: number,
  nowMs: number,
): string {
  const phrases = CREATURE_STATUS_PHRASES[category];
  const bucket = Math.floor(nowMs / CYCLE_MS);
  return phrases[modulo(bucket + entityId, phrases.length)];
}
